version: 2
project_name: gke-auth-plugin

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.appVersion={{.Version}} # Inject the version into the binary
    binary: gke-auth-plugin

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: ZeitOnline
    name: gke-auth-plugin
